"use strict";
var lname;
lname = 'Pradeep';
var newname = lname.toUpperCase();
console.log(newname);
var dob = '25';
var res = parseInt(dob);
console.log("result ------>  ", res);
var bool;
console.log(bool);
